### ISSUE TITLE
Web GUI

### ISSUE THREAD

**Issue by khromov** [pcfreak30/WordPress-Profiler#1]
👋 Came across this process and it looks very good. Are there any thoughts about writing a simple web GUI that won't require us to feed the data into ElasticSearch to analyze it?

**Comment by pcfreak30** [comment]
At this time, I do not have an interest in creating one. I have tackled the problem of the engine/framework and a practical reporter to send to ElasticSearch which can be forked and used for other purposes as well. I am open to anyone else creating a project for this. With the elastic search aspect, you could create one in any stack and not just in WordPress.

TL;DR: I created the backend, I bow to others to create the frontend :)

**Comment by khromov** [comment]
@pcfreak30 Alright, gotcha. :-)

I think that creating a UI that can represent all of the complexities of WP execution will probably take at least as long as collecting the data if not longer, so I hope somebody is up for that challenge.

For people looking for an existing UI, check the Query Monitor project which covers most of what this plugin does (on a per-request level, rather than in an aggregated manner).

**Comment by pcfreak30** [comment]
```For people looking for an existing UI, check the Query Monitor project which covers most of what this plugin does (on a per-request level, rather than in an aggregated manner).```

@khromov 

Yes, I am aware of that one myself. In fact, see https://github.com/johnbillion/query-monitor/issues/260#issuecomment-557793313 :)

The goal here was to make something that's silent and not directly interactive. Though technically, you could potentially add a query monitor reporter that just calls `generate_report` and works with the profiler output at that given moment.
